In [12]:
%load_ext autoreload
%autoreload 2

In [14]:
import sys
import os

# Add parent folder to Python path
sys.path.append(os.path.abspath(".."))

In [15]:
from nutrimap_app.data_prep_marie import clean_food_data

df = clean_food_data()

In [16]:
from nutrimap_app.category_mapping import assign_food_group
df["food_category"] = df.apply(assign_food_group, axis=1)

df.sample(100, random_state=45)

,food_item,energy_kcal,data_type,fat_g,satfat_g,carbs_g,protein_g,fiber_g,energy_kcal_calculated,food_category
7088,"Lamb, New Zealand, imported, square-cut should...",255.0,sr_legacy_food,14.56,5.476,0.00,31.06,0.0,255.3,meat_red
2459,"Cereals ready-to-eat, POST, HONEY BUNCHES OF O...",409.0,sr_legacy_food,7.30,0.800,79.60,7.70,5.5,414.9,sweets_snacks
1238,Catsup,101.0,sr_legacy_food,0.10,0.014,27.40,1.04,0.3,114.7,mixed/other
4130,"Chicken breast tenders, breaded, uncooked",263.0,sr_legacy_food,15.75,3.260,15.01,14.73,1.1,260.7,dairy_fatty
3174,"Potatoes, au gratin, home-prepared from recipe...",552.0,sr_legacy_food,7.59,3.530,11.27,5.06,1.8,133.6,dairy_lean
...,...,...,...,...,...,...,...,...,...,...
6179,"Infant formula, ABBOTT NUTRITION, SIMILAC, ISO...",276.0,sr_legacy_food,3.59,1.166,6.70,1.61,0.0,65.6,mixed/other
3945,"Spices, paprika",1181.0,sr_legacy_food,12.89,2.140,53.99,14.14,34.9,388.5,dairy_fatty
1882,"Kale, frozen, unprepared",28.0,sr_legacy_food,0.46,0.059,4.88,2.66,2.0,34.3,nonstarchy_veg
7296,"Cereals ready-to-eat, MALT-O-MEAL, CHOCOLATE M...",392.0,sr_legacy_food,3.67,1.600,88.18,3.50,2.5,399.8,dairy_fatty
4193,"SMART SOUP, Greek Minestrone",40.0,sr_legacy_food,0.53,0.000,8.40,1.70,2.7,45.2,fruit_sweet

In [20]:
from nutrimap_app.plate_role_mapping import assign_plate_component

df["plate_component"] = df.apply(assign_plate_component, axis=1)

df.sample(100, random_state=55)

[autoreload of nutrimap_app.plate_role_mapping failed: Traceback (most recent call last):
  File "/Users/marieahluwalia/.pyenv/versions/nutrimap/lib/python3.12/site-packages/IPython/extensions/autoreload.py", line 325, in check
    superreload(m, reload, self.old_objects)
  File "/Users/marieahluwalia/.pyenv/versions/nutrimap/lib/python3.12/site-packages/IPython/extensions/autoreload.py", line 580, in superreload
    module = reload(module)
             ^^^^^^^^^^^^^^
  File "/Users/marieahluwalia/.pyenv/versions/3.12.9/lib/python3.12/importlib/__init__.py", line 131, in reload
    _bootstrap._exec(spec, module)
  File "<frozen importlib._bootstrap>", line 866, in _exec
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/Users/marieahluwalia/code/MarieAhluwalia/nutrimap/nutrimap_app/plate_role_mapping.py", line 93
    if nonstarchy_veg_like #or fruit_like:
                           ^^^^^^^^^^^^^^^^
SyntaxError: expected ':'
]

,food_item,energy_kcal,data_type,fat_g,satfat_g,carbs_g,protein_g,fiber_g,energy_kcal_calculated,food_category,plate_component
930,"Pork, cured, ham with natural juices, spiral s...",129.0,sr_legacy_food,5.75,1.833,1.18,18.66,0.0,131.1,fish_seafood,protein
7066,"Game meat, elk, ground, raw",172.0,sr_legacy_food,8.82,3.469,0.00,21.76,0.0,166.4,eggs,protein
1967,"Brussels sprouts, frozen, cooked, boiled, drai...",42.0,sr_legacy_food,0.39,0.081,8.32,3.64,4.1,51.4,fruit_sweet,protein
7535,"Lamb, Australian, imported, fresh, leg, trotte...",734.0,sr_legacy_food,9.73,4.464,0.00,21.95,0.0,175.4,meat_red,protein
7468,"Alcoholic beverage, wine, table, white",82.0,sr_legacy_food,0.00,0.000,2.60,0.07,0.0,10.7,mixed/other,other
...,...,...,...,...,...,...,...,...,...,...,...
3856,"Beef, chuck, short ribs, boneless, separable l...",317.0,sr_legacy_food,24.05,10.638,0.00,25.26,0.0,317.5,meat_red,protein
3754,"Chicken, broilers or fryers, rotisserie, origi...",197.0,sr_legacy_food,9.53,2.223,0.00,27.69,0.0,196.5,poultry,protein
6868,"Fish, tuna, light, canned in oil, without salt...",830.0,sr_legacy_food,8.21,1.534,0.00,29.13,0.0,190.4,poultry,protein
1852,"Asparagus, canned, drained solids",19.0,sr_legacy_food,0.65,0.147,2.46,2.14,1.6,24.2,mixed/other,protein
3889,"Cream, sour, cultured",198.0,sr_legacy_food,19.35,10.140,4.63,2.44,0.0,202.4,oils_fats,other

In [19]:
df[df["food_item"].str.contains("potato", case=False, na=False)].sample(30, random_state=42)

,food_item,energy_kcal,data_type,fat_g,satfat_g,carbs_g,protein_g,fiber_g,energy_kcal_calculated,food_category,plate_component
1066,"Sweet potato, cooked, baked in skin, flesh, wi...",90.0,sr_legacy_food,0.15,0.052,20.71,2.01,3.3,92.2,fruit_sweet,vegetables
2973,"Potatoes, frozen, whole, cooked, boiled, drain...",272.0,sr_legacy_food,0.13,0.034,14.52,1.98,1.4,67.2,mixed/other,vegetables
7437,"Snacks, Pretzels, gluten- free made with corns...",389.0,sr_legacy_food,6.67,3.307,78.62,3.52,3.3,388.6,dairy_fatty,protein
3101,"Potatoes, canned, solids and liquids",44.0,sr_legacy_food,0.11,0.029,9.89,1.20,1.4,45.4,mixed/other,vegetables
3105,"Potatoes, au gratin, dry mix, unprepared",314.0,sr_legacy_food,3.70,2.323,74.31,8.90,4.1,366.1,dairy_fatty,protein
2629,"Potatoes, mashed, home-prepared, whole milk an...",474.0,sr_legacy_food,4.20,0.745,16.94,1.96,1.5,113.4,fruit_sweet,vegetables
1127,Corned beef and potatoes in tortilla (Apache),224.0,sr_legacy_food,8.31,3.366,29.35,7.91,1.5,223.8,dairy_fatty,protein
2304,"Snacks, potato chips, made from dried potatoes...",551.0,sr_legacy_food,37.00,9.570,50.60,7.00,3.4,563.4,dairy_fatty,protein
1909,"Potatoes, frozen, french fried, par fried, ext...",1393.0,sr_legacy_food,18.71,5.960,39.68,3.55,3.2,341.3,dairy_fatty,protein
2619,"Potatoes, russet, flesh and skin, raw (Include...",79.0,sr_legacy_food,0.08,0.026,18.07,2.14,1.3,81.6,mixed/other,other
2697,"Potatoes, boiled, cooked in skin, flesh, with ...",364.0,sr_legacy_food,0.10,0.026,20.13,1.87,2.0,88.9,fruit_sweet,vegetables
5971,"Beef, corned beef hash, with potato, canned",164.0,sr_legacy_food,10.24,4.320,9.27,8.73,1.1,164.2,dairy_fatty,protein
1183,"Potato wedges, frozen (Includes foods for USDA...",129.0,sr_legacy_food,2.20,0.550,25.46,2.70,2.0,132.4,mixed/other,carbs
6159,"Babyfood, dinner, sweet potatoes and chicken, ...",310.0,sr_legacy_food,2.17,0.572,11.04,2.51,1.3,73.7,mixed/other,vegetables
2698,"Potatoes, microwaved, cooked, in skin, skin wi...",554.0,sr_legacy_food,0.10,0.026,29.63,4.39,5.5,137.0,mixed/other,carbs
2972,"Potatoes, hash brown, frozen, with butter sauc...",745.0,sr_legacy_food,8.79,3.373,24.13,2.46,3.8,185.5,mixed/other,other
3172,"Potatoes, microwaved, cooked in skin, flesh, w...",420.0,sr_legacy_food,0.10,0.026,23.28,2.10,1.6,102.4,fruit_sweet,vegetables
1030,"Potatoes, french fried, steak fries, salt adde...",148.0,sr_legacy_food,3.76,0.737,26.98,2.57,2.6,152.0,mixed/other,carbs
653,"Sweet Potato puffs, frozen, unprepared",161.0,sr_legacy_food,3.58,0.310,30.72,1.36,1.9,160.5,mixed/other,other
3110,"Potatoes, french fried, shoestring, salt added...",194.0,sr_legacy_food,6.76,1.267,31.66,2.90,2.8,199.1,mixed/other,other
1691,"Babyfood, juice, apple-sweet potato",47.0,sr_legacy_food,0.10,0.030,11.40,0.30,0.5,47.7,mixed/other,other
1946,"Sweet potato, frozen, cooked, baked, without salt",419.0,sr_legacy_food,0.12,0.025,23.40,1.71,1.8,101.5,fruit_sweet,vegetables
4925,"Babyfood, vegetables, sweet potatoes strained",57.0,sr_legacy_food,0.10,0.021,13.20,1.10,1.5,58.1,fruit_sweet,vegetables
2631,"Potatoes, mashed, dehydrated, granules without...",1556.0,sr_legacy_food,0.54,0.138,85.51,8.22,7.1,379.8,sweets_snacks,carbs
4926,"Babyfood, vegetables, sweet potatoes, junior",60.0,sr_legacy_food,0.10,0.021,14.00,1.10,1.5,61.3,fruit_sweet,vegetables
1695,"Snacks, potato chips, white, restructured, baked",469.0,sr_legacy_food,18.20,2.631,71.40,5.00,4.8,469.4,dairy_fatty,protein
3092,"Potatoes, white, flesh and skin, baked",385.0,sr_legacy_food,0.15,0.040,21.08,2.10,2.1,94.1,fruit_sweet,vegetables
1733,"Potatoes, canned, drained solids, no salt added",250.0,sr_legacy_food,0.20,0.051,13.60,1.40,2.4,61.8,fruit_sweet,vegetables
2673,"Sweet potato, cooked, candied, home-prepared",164.0,sr_legacy_food,3.54,2.171,32.12,0.89,2.1,163.9,mixed/other,other
2630,"Potatoes, scalloped, home-prepared with butter",88.0,sr_legacy_food,3.68,2.255,10.78,2.87,1.9,87.7,fruit_sweet,vegetables