In [2]:
import sys, os
sys.path.append(os.path.abspath("../"))

In [3]:

from nutrimap_app.KMeanModel import build_kmeans_model

model, df_clusters = build_kmeans_model()

In [4]:
from nutrimap_app.KMeanModel import CLUSTERED_DATA_PATH
import pandas as pd

df_clusters = pd.read_csv(CLUSTERED_DATA_PATH)
df_clusters.sample(30, random_state=64)

,food_item,fat_g,satfat_g,carbs_g,protein_g,fiber_g,energy_kcal_calculated,cluster
4898,"Lamb, New Zealand, imported, loin saddle, sepa...",5.32,1.960,0.00,20.86,0.0,131.3,4
185,"Candies, NESTLE, CHUNKY Bar",27.50,12.500,60.40,7.50,2.5,519.1,1
1586,"Pears, dried, sulfured, stewed, without added ...",0.31,0.017,33.81,0.91,6.4,141.7,0
7283,"Beverages, fruit punch-flavor drink, powder, w...",0.01,0.006,9.47,0.00,0.0,38.0,0
3496,"SMART SOUP, Moroccan Chick Pea",1.06,0.180,9.70,2.00,3.1,56.3,0
3280,"Babyfood, fruit, pears and pineapple, strained",0.10,0.007,10.90,0.30,2.6,45.7,0
3416,"Turkey, whole, breast, meat only, raw",1.48,0.289,0.14,23.66,0.0,108.5,4
1088,"Tomatillos, raw",1.02,0.139,5.84,0.96,1.9,36.4,0
3452,"Turkey, retail parts, drumstick, meat and skin...",9.37,2.307,0.00,28.21,0.0,197.2,4
6476,"Soy flour, defatted",1.22,0.136,33.92,51.46,17.5,352.5,4
407,"Pork, fresh, variety meats and by-products, st...",10.14,4.025,0.00,16.85,0.0,158.7,4
1623,"Pork, cured, ham and water product, rump, bone...",12.13,3.984,1.35,16.09,0.0,178.9,4
1287,"Candies, YORK BITES",7.32,4.430,81.64,1.78,2.0,399.6,1
4784,"Lamb, cubed for stew or kabob (leg and shoulde...",8.80,3.150,0.00,33.69,0.0,214.0,4
5076,"Crackers, whole-wheat, low salt",17.20,3.393,68.60,8.80,10.5,464.4,1
246,"Sausage, turkey and pork, fresh, bulk, patty o...",23.00,7.950,0.70,22.70,0.0,300.6,2
4990,"Cookies, fortune",2.70,0.669,84.00,4.20,1.6,377.1,1
6691,"Turkey, ground, 85% lean, 15% fat, raw",12.54,3.414,0.00,16.90,0.0,180.5,4
6895,"Beef, top loin petite roast, boneless, separab...",11.20,3.666,0.90,27.10,0.0,212.8,4
1869,"Beef, chuck, under blade pot roast or steak, b...",6.07,2.580,0.31,21.13,0.0,140.4,4
4477,"Cheese, cottage, creamed, large or small curd",4.30,1.718,3.38,11.12,0.0,96.7,0
1974,"Beef, top sirloin, steak, separable lean and f...",21.06,8.180,0.00,28.77,0.0,304.6,4
3036,"Buckwheat flour, whole-groat",3.10,0.677,70.59,12.62,10.0,360.7,1
4610,"Infant formula, ABBOTT NUTRITION, SIMILAC, ADV...",6.89,2.401,13.52,2.64,0.0,126.6,0
2623,Buckwheat,3.40,0.741,71.50,13.25,10.0,369.6,1
2298,"Oranges, raw, with peel",0.30,0.035,15.50,1.30,4.5,69.9,0
6365,"Beverages, Fruit punch drink, frozen concentra...",0.00,0.001,11.66,0.06,0.1,46.9,0
133,"Bagels, wheat",1.53,0.000,48.89,10.20,4.1,250.1,1
1505,"Cereals ready-to-eat, frosted oat cereal with ...",3.33,0.620,84.70,7.10,4.3,397.2,1
1006,"Fish, salmon, sockeye (red), raw (Alaska Native)",7.28,1.007,0.00,21.94,0.0,153.3,4

In [5]:
import importlib
import nutrimap_app.KMeanModel as km

# reload in case you just edited KMeanModel.py
importlib.reload(km)

# 1) run main clustering
model, df_clusters = km.build_kmeans_model()

# 2) run subclustering on that result
df_final = km.subclustering(df_clusters)

# df_final.sample(30, random_state=42)
df_final[df_final["cluster"] == 3].sample(20, random_state=44)

,food_item,fat_g,satfat_g,carbs_g,protein_g,fiber_g,energy_kcal_calculated,cluster,subcluster
4341,"Beef, Australian, imported, Wagyu, external fa...",63.27,22.504,0.00,6.54,0.0,595.6,3,-1
3643,"Salad dressing, mayonnaise, soybean and safflo...",79.40,8.600,2.70,1.10,0.0,729.8,3,-1
449,"Pork, fresh, backfat, raw",88.69,32.210,0.00,2.92,0.0,809.9,3,-1
3665,"Oil, apricot kernel",100.00,6.300,0.00,0.00,0.0,900.0,3,-1
6241,"Oil, industrial, soy (partially hydrogenated )...",100.00,28.421,0.00,0.00,0.0,900.0,3,-1
3649,"Oil, sesame, salad or cooking",100.00,14.200,0.00,0.00,0.0,900.0,3,-1
858,"Pork, fresh, variety meats and by-products, jo...",69.61,25.260,0.00,6.38,0.0,652.0,3,-1
4032,"Salad dressing, french, home recipe",70.20,12.600,3.40,0.10,0.0,645.8,3,-1
5008,"Oil, industrial, canola (partially hydrogenate...",100.00,10.117,0.00,0.00,0.0,900.0,3,-1
5018,"Oil, vegetable, soybean, refined",100.00,15.251,0.00,0.00,0.0,900.0,3,-1
5725,"Beef, New Zealand, imported, intermuscular fat...",63.78,28.500,0.01,6.97,0.0,601.9,3,-1
3650,"Oil, sunflower, linoleic (less than 60%)",100.00,10.100,0.00,0.00,0.0,900.0,3,-1
3233,"Nuts, hazelnuts or filberts, dry roasted, with...",62.40,4.511,17.60,15.03,9.4,692.1,3,-1
3651,"Margarine, regular, hard, soybean (hydrogenated)",80.50,16.700,0.90,0.90,0.0,731.7,3,-1
4987,"Margarine-like, margarine-butter blend, soybea...",80.32,14.198,0.77,0.31,0.0,727.2,3,-1
6238,"Oil, industrial, palm kernel (hydrogenated), c...",100.00,93.701,0.00,0.00,0.0,900.0,3,-1
4047,"Margarine, margarine-like vegetable oil spread...",68.29,16.688,0.59,0.07,0.0,617.2,3,-1
4034,"Salad dressing, mayonnaise, soybean oil, witho...",79.40,11.800,2.70,1.10,0.0,729.8,3,-1
4043,"Oil, hazelnut",100.00,7.400,0.00,0.00,0.0,900.0,3,-1
3658,"Oil, sunflower, linoleic, (approx. 65%)",100.00,10.300,0.00,0.00,0.0,900.0,3,-1

In [6]:
from nutrimap_app.KMeanModel import build_kmeans_model, subclustering, assign_plate_role

model, df_clusters = build_kmeans_model()

df_sub = subclustering(df_clusters)
df_final = assign_plate_role(df_sub)

df_final[["food_item", "cluster", "subcluster", "plate_role"]].sample(20)

,food_item,cluster,subcluster,plate_role
2111,"Beef, composite of trimmed retail cuts, separa...",4,-1,protein
6896,"Lima beans, thin seeded (baby), mature seeds, raw",1,0,carbs
6175,"Infant formula, MEAD JOHNSON, ENFAMIL, LIPIL, ...",0,1,protein
2451,"OLIVE GARDEN, lasagna classico",4,-1,protein
4695,"KFC, Fried Chicken, EXTRA CRISPY, Skin and Bre...",2,-1,protein
2127,"Beef, rib, whole (ribs 6-12), separable lean a...",2,-1,protein
386,"Mollusks, scallop, (bay and sea), cooked, steamed",4,-1,protein
3984,"Babyfood, cookie, baby, fruit",1,1,other
1643,"Infant formula, MEAD JOHNSON, ENFAMIL, NUTRAMI...",1,1,other
5501,"Chicken, dark meat, drumstick, meat only, with...",4,-1,protein
5489,"Ostrich, oyster, cooked",4,-1,protein
7339,"Beef, top loin petite roast, boneless, separab...",4,-1,protein
6215,"Fish oil, cod liver",3,-1,fat
334,"Candies, MARS SNACKFOOD US, M&M's Peanut Butte...",1,1,other
3001,"TACO BELL, BURRITO SUPREME with steak",0,1,protein
4420,"Beef, tenderloin, steak, separable lean only, ...",4,-1,protein
4320,"Avocados, raw, Florida",0,1,protein
7004,"Veal, variety meats and by-products, pancreas,...",4,-1,protein
5652,"Cereals, CREAM OF WHEAT, 1 minute cook time, dry",1,0,carbs
1525,"Frozen yogurts, chocolate, soft-serve",0,1,protein